// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RMS.Infrastructure.Data;

#nullable disable

namespace RMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RmsDbContext))]
    [Migration("20260822084348_AddNotificationCenter")]
    partial class AddNotificationCenter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalDelegation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DelegateUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DelegatorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DelegateUserId");

                    b.HasIndex("DelegatorUserId", "StartDate", "EndDate");

                    b.ToTable("ApprovalDelegations", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("ApprovalWorkflows", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowCategoryLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalWorkflowVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisitionCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionCategoryId");

                    b.HasIndex("ApprovalWorkflowVersionId", "RequisitionCategoryId")
                        .IsUnique();

                    b.ToTable("ApprovalWorkflowCategoryLinks", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowSlaConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalWorkflowStageId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationUnit")
                        .HasColumnType("integer");

                    b.Property<int>("DurationValue")
                        .HasColumnType("integer");

                    b.Property<bool>("EscalateOnBreach")
                        .HasColumnType("boolean");

                    b.Property<int?>("EscalationApproverRole")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EscalationApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Reminder50PercentEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("Reminder80PercentEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowStageId")
                        .IsUnique();

                    b.HasIndex("EscalationApproverUserId");

                    b.ToTable("ApprovalWorkflowSlaConfigurations", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalWorkflowVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CapturesEstimatedCost")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowVersionId", "StageOrder")
                        .IsUnique();

                    b.ToTable("ApprovalWorkflowStages", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowStageCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalWorkflowStageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConditionType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowStageId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ApprovalWorkflowStageConditions", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AppliesToAllCategories")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ApprovalWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoutingMode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ApprovalWorkflowVersions", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorRole")
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryCostCenterLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CostCenterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("CategoryId", "CostCenterId")
                        .IsUnique();

                    b.ToTable("CategoryCostCenterLinks", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("HelpText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryFieldOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.ToTable("CategoryFieldOptions", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryFieldValidationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedFileExtensions")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxFileSizeMb")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RegexPattern")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId")
                        .IsUnique();

                    b.ToTable("CategoryFieldValidationRules", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryItems", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("CategoryTemplateVersions", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("CostCenters", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.EligibilityPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryItemId");

                    b.HasIndex("CompanyId", "CategoryId", "CategoryItemId");

                    b.ToTable("EligibilityPolicies", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.EligibilityPolicyCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CriterionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("EligibilityPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EligibilityPolicyId");

                    b.ToTable("EligibilityPolicyCriteria", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.EligibilityPolicyReplacementRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationUnit")
                        .HasColumnType("integer");

                    b.Property<int>("DurationValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("EligibilityPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EligibilityPolicyId")
                        .IsUnique();

                    b.ToTable("EligibilityPolicyReplacementRules", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EventType")
                        .IsUnique();

                    b.ToTable("NotificationPreferences", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("InAppMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "EventType")
                        .IsUnique();

                    b.ToTable("NotificationTemplates", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.PartialApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DeclinedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequisitionApprovalActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisitionItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionApprovalActionId");

                    b.HasIndex("RequisitionItemId");

                    b.ToTable("PartialApprovalDecisions", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.Requisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryVersionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("NeedByDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequisitionNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UrgencyJustification")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("RequisitionNumber")
                        .IsUnique()
                        .HasFilter("\"RequisitionNumber\" IS NOT NULL");

                    b.ToTable("Requisitions", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalWorkflowStageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisitionApprovalProcessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SlaDueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SlaPausedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("SlaPausedDurationTotal")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("SlaStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StageOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowStageId");

                    b.HasIndex("RequisitionApprovalProcessId", "StageOrder")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (0, 1, 6)");

                    b.ToTable("RequisitionApprovals", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApprovalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorRole")
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CapturedEstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DelegatedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EscalatedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisitionApprovalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionApprovalId");

                    b.ToTable("RequisitionApprovalActions", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApprovalAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasActed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OriginalApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisitionApprovalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoleFanoutGroupId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("RequisitionApprovalId");

                    b.ToTable("RequisitionApprovalAssignments", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApprovalProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalWorkflowVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentStageOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowVersionId");

                    b.HasIndex("RequisitionId")
                        .IsUnique();

                    b.ToTable("RequisitionApprovalProcesses", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UploadedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequisitionAttachments", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClonedFromCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCostCenterMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProjectCodeRequirement")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("RequisitionCategories", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequisitionFieldValues", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("FulfilledQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryItemId");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequisitionItems", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionProcurementLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("QuantityFulfilledThisAction")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequisitionItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisitionProcurementRecordId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionItemId");

                    b.HasIndex("RequisitionProcurementRecordId");

                    b.ToTable("RequisitionProcurementLineItems", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionProcurementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorRole")
                        .HasColumnType("text");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TotalProcurementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequisitionProcurementRecords", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequisitionStatusHistories", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int?>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Grade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.WorkflowApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalWorkflowStageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ApproverRole")
                        .HasColumnType("integer");

                    b.Property<int>("ApproverType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FallbackApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowStageId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("FallbackApproverUserId");

                    b.ToTable("WorkflowApprovers", (string)null);
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalDelegation", b =>
                {
                    b.HasOne("RMS.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.User", "DelegateUser")
                        .WithMany()
                        .HasForeignKey("DelegateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.User", "DelegatorUser")
                        .WithMany()
                        .HasForeignKey("DelegatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DelegateUser");

                    b.Navigation("DelegatorUser");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.HasOne("RMS.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowCategoryLink", b =>
                {
                    b.HasOne("RMS.Domain.Entities.ApprovalWorkflowVersion", "ApprovalWorkflowVersion")
                        .WithMany("CategoryLinks")
                        .HasForeignKey("ApprovalWorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.RequisitionCategory", "RequisitionCategory")
                        .WithMany()
                        .HasForeignKey("RequisitionCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflowVersion");

                    b.Navigation("RequisitionCategory");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowSlaConfiguration", b =>
                {
                    b.HasOne("RMS.Domain.Entities.ApprovalWorkflowStage", "ApprovalWorkflowStage")
                        .WithOne("Sla")
                        .HasForeignKey("RMS.Domain.Entities.ApprovalWorkflowSlaConfiguration", "ApprovalWorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.User", "EscalationApproverUser")
                        .WithMany()
                        .HasForeignKey("EscalationApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovalWorkflowStage");

                    b.Navigation("EscalationApproverUser");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowStage", b =>
                {
                    b.HasOne("RMS.Domain.Entities.ApprovalWorkflowVersion", "ApprovalWorkflowVersion")
                        .WithMany("Stages")
                        .HasForeignKey("ApprovalWorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflowVersion");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowStageCondition", b =>
                {
                    b.HasOne("RMS.Domain.Entities.ApprovalWorkflowStage", "ApprovalWorkflowStage")
                        .WithMany("Conditions")
                        .HasForeignKey("ApprovalWorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.RequisitionCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovalWorkflowStage");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowVersion", b =>
                {
                    b.HasOne("RMS.Domain.Entities.ApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("Versions")
                        .HasForeignKey("ApprovalWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflow");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryCostCenterLink", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RequisitionCategory", "Category")
                        .WithMany("CostCenterLinks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CostCenter");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryFieldDefinition", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RequisitionCategory", "Category")
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryFieldOption", b =>
                {
                    b.HasOne("RMS.Domain.Entities.CategoryFieldDefinition", "FieldDefinition")
                        .WithMany("Options")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryFieldValidationRule", b =>
                {
                    b.HasOne("RMS.Domain.Entities.CategoryFieldDefinition", "FieldDefinition")
                        .WithOne("ValidationRule")
                        .HasForeignKey("RMS.Domain.Entities.CategoryFieldValidationRule", "FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryItem", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RequisitionCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryTemplateVersion", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RequisitionCategory", "Category")
                        .WithMany("Versions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CostCenter", b =>
                {
                    b.HasOne("RMS.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RMS.Domain.Entities.EligibilityPolicy", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RequisitionCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.CategoryItem", "CategoryItem")
                        .WithMany()
                        .HasForeignKey("CategoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CategoryItem");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RMS.Domain.Entities.EligibilityPolicyCriterion", b =>
                {
                    b.HasOne("RMS.Domain.Entities.EligibilityPolicy", "EligibilityPolicy")
                        .WithMany("Criteria")
                        .HasForeignKey("EligibilityPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EligibilityPolicy");
                });

            modelBuilder.Entity("RMS.Domain.Entities.EligibilityPolicyReplacementRule", b =>
                {
                    b.HasOne("RMS.Domain.Entities.EligibilityPolicy", "EligibilityPolicy")
                        .WithOne("ReplacementRule")
                        .HasForeignKey("RMS.Domain.Entities.EligibilityPolicyReplacementRule", "EligibilityPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EligibilityPolicy");
                });

            modelBuilder.Entity("RMS.Domain.Entities.PartialApprovalDecision", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RequisitionApprovalAction", "RequisitionApprovalAction")
                        .WithMany("PartialDecisions")
                        .HasForeignKey("RequisitionApprovalActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.RequisitionItem", "RequisitionItem")
                        .WithMany()
                        .HasForeignKey("RequisitionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequisitionApprovalAction");

                    b.Navigation("RequisitionItem");
                });

            modelBuilder.Entity("RMS.Domain.Entities.Requisition", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RequisitionCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("CostCenter");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApproval", b =>
                {
                    b.HasOne("RMS.Domain.Entities.ApprovalWorkflowStage", "ApprovalWorkflowStage")
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.RequisitionApprovalProcess", "RequisitionApprovalProcess")
                        .WithMany("StageInstances")
                        .HasForeignKey("RequisitionApprovalProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflowStage");

                    b.Navigation("RequisitionApprovalProcess");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApprovalAction", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RequisitionApproval", "RequisitionApproval")
                        .WithMany("Actions")
                        .HasForeignKey("RequisitionApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequisitionApproval");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApprovalAssignment", b =>
                {
                    b.HasOne("RMS.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.RequisitionApproval", "RequisitionApproval")
                        .WithMany("Assignments")
                        .HasForeignKey("RequisitionApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("RequisitionApproval");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApprovalProcess", b =>
                {
                    b.HasOne("RMS.Domain.Entities.ApprovalWorkflowVersion", "ApprovalWorkflowVersion")
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.Requisition", "Requisition")
                        .WithOne("ApprovalProcess")
                        .HasForeignKey("RMS.Domain.Entities.RequisitionApprovalProcess", "RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflowVersion");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionAttachment", b =>
                {
                    b.HasOne("RMS.Domain.Entities.Requisition", "Requisition")
                        .WithMany("Attachments")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionCategory", b =>
                {
                    b.HasOne("RMS.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionFieldValue", b =>
                {
                    b.HasOne("RMS.Domain.Entities.CategoryFieldDefinition", "FieldDefinition")
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.Requisition", "Requisition")
                        .WithMany("FieldValues")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionItem", b =>
                {
                    b.HasOne("RMS.Domain.Entities.CategoryItem", "CategoryItem")
                        .WithMany()
                        .HasForeignKey("CategoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RMS.Domain.Entities.Requisition", "Requisition")
                        .WithMany("Items")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryItem");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionProcurementLineItem", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RequisitionItem", "RequisitionItem")
                        .WithMany()
                        .HasForeignKey("RequisitionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.RequisitionProcurementRecord", "RequisitionProcurementRecord")
                        .WithMany("LineItems")
                        .HasForeignKey("RequisitionProcurementRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequisitionItem");

                    b.Navigation("RequisitionProcurementRecord");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionProcurementRecord", b =>
                {
                    b.HasOne("RMS.Domain.Entities.Requisition", "Requisition")
                        .WithMany("ProcurementRecords")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionStatusHistory", b =>
                {
                    b.HasOne("RMS.Domain.Entities.Requisition", "Requisition")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("RMS.Domain.Entities.User", b =>
                {
                    b.HasOne("RMS.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RMS.Domain.Entities.WorkflowApprover", b =>
                {
                    b.HasOne("RMS.Domain.Entities.ApprovalWorkflowStage", "ApprovalWorkflowStage")
                        .WithMany("Approvers")
                        .HasForeignKey("ApprovalWorkflowStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Domain.Entities.User", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Domain.Entities.User", "FallbackApproverUser")
                        .WithMany()
                        .HasForeignKey("FallbackApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovalWorkflowStage");

                    b.Navigation("ApproverUser");

                    b.Navigation("FallbackApproverUser");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowStage", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Conditions");

                    b.Navigation("Sla");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ApprovalWorkflowVersion", b =>
                {
                    b.Navigation("CategoryLinks");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CategoryFieldDefinition", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("ValidationRule");
                });

            modelBuilder.Entity("RMS.Domain.Entities.EligibilityPolicy", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("ReplacementRule");
                });

            modelBuilder.Entity("RMS.Domain.Entities.Requisition", b =>
                {
                    b.Navigation("ApprovalProcess");

                    b.Navigation("Attachments");

                    b.Navigation("FieldValues");

                    b.Navigation("Items");

                    b.Navigation("ProcurementRecords");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApproval", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApprovalAction", b =>
                {
                    b.Navigation("PartialDecisions");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionApprovalProcess", b =>
                {
                    b.Navigation("StageInstances");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionCategory", b =>
                {
                    b.Navigation("CostCenterLinks");

                    b.Navigation("FieldDefinitions");

                    b.Navigation("Items");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RequisitionProcurementRecord", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
